spring.application.name=backend
 spring.data.mongodb.uri=<<Your Mongo Db atlas URl>>
#spring.data.mongodb.uri=mongodb://localhost:27017/MyData
spring.data.mongodb.database=MyData

spring.security.user.name=admin
spring.security.user.password=admin
server.port=8080
spring.profiles.active=default
spring.main.allow-circular-references=true
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.mongodb=DEBUG

cloudflare.r2.endpoint=CLoudlfare endpoint
cloudflare.r2.bucket=my-data
cloudflare.r2.accessKey=Cloudflare acces key
cloudflare.r2.secretKey=Cloudflare secret key


# Multipart File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS Configuration (adjust for your frontend URL)
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*

jwt.secret=yourVeryLongAndSecureSecretKeyHereAtLeast32Characters
jwt.expiration=86400000
